### Check pytorch version

In [1]:
import torch
torch.__version__

'2.1.1+cu121'

# Scalar | Zero dimension tensor

In [2]:
# scalar 
scalar = torch.tensor(8)
print(type(scalar))
print(scalar)

<class 'torch.Tensor'>
tensor(8)


In [3]:
# check dimenasion of tensor 
scalar.ndim 

0

In [4]:
# Get the  python within a tensor (only works with one-element tensors)

scalar.item()


8

# Vector | One dimension tensor

In [5]:
# Vector 
vector = torch.tensor([1,2, 3])
vector

tensor([1, 2, 3])

In [6]:
# check the num of dimensio of vector 
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

# Matrix | 2 dimensions tensor

In [8]:
MATRIX = torch.tensor([[1,2],
                       [3,4],
                       [1,2]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [1, 2]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 2])

# Tensor | n  dimensional array of numbers

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                        [1,2,3],
                        [1,2,3]],
                       
                       [[1,2,3],
                       [1,2,3],
                       [1,2,3]]])

TENSOR

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([2, 3, 3])

# Create reandom tensor of size (3,4)

In [33]:
random_tensor = torch.rand(size=(2,4, 3))
random_tensor, random_tensor.dtype 

(tensor([[[4.9089e-01, 2.7354e-01, 6.8305e-01],
          [6.9671e-01, 6.0147e-01, 4.6982e-01],
          [2.9987e-04, 9.9240e-01, 3.4595e-01],
          [6.1854e-01, 1.8557e-01, 1.8227e-01]],
 
         [[6.0469e-01, 3.0670e-01, 3.8131e-01],
          [1.4073e-01, 4.3937e-01, 2.2607e-01],
          [3.0355e-02, 9.0913e-01, 5.9684e-01],
          [5.3448e-01, 6.3846e-01, 2.7654e-01]]]),
 torch.float32)

In [38]:
ran_image_size_tensor = torch.rand(size=(224, 224, 3))
ran_image_size_tensor

tensor([[[0.6274, 0.4035, 0.3702],
         [0.2750, 0.9325, 0.3161],
         [0.1984, 0.5884, 0.0572],
         ...,
         [0.6439, 0.4684, 0.6763],
         [0.4928, 0.0443, 0.2066],
         [0.0963, 0.0292, 0.5701]],

        [[0.3603, 0.4655, 0.6273],
         [0.3962, 0.7568, 0.2483],
         [0.3697, 0.0169, 0.3613],
         ...,
         [0.7903, 0.8981, 0.1855],
         [0.6370, 0.5706, 0.9203],
         [0.1657, 0.3245, 0.7476]],

        [[0.5698, 0.5143, 0.6990],
         [0.0197, 0.9083, 0.0681],
         [0.1667, 0.8856, 0.7707],
         ...,
         [0.6913, 0.9433, 0.0467],
         [0.0515, 0.0488, 0.6574],
         [0.9046, 0.1993, 0.2354]],

        ...,

        [[0.0953, 0.4891, 0.4546],
         [0.3604, 0.6284, 0.4444],
         [0.0058, 0.6602, 0.7245],
         ...,
         [0.6976, 0.2932, 0.6363],
         [0.8171, 0.7066, 0.1319],
         [0.0285, 0.3149, 0.9594]],

        [[0.7510, 0.9566, 0.9042],
         [0.6489, 0.7642, 0.9569],
         [0.

In [39]:
ran_image_size_tensor.shape, ran_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [40]:
zeros = torch.zeros(size=(2,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [41]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [43]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_20223/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [45]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [47]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) 

float_16_tensor.dtype

torch.float16

In [48]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9642, 0.0181, 0.5530, 0.6731],
        [0.9620, 0.4392, 0.4879, 0.4204],
        [0.2085, 0.0061, 0.2423, 0.8475]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (tensor operations)

In [49]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [50]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [51]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [52]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [53]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [54]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [55]:
tensor

tensor([1, 2, 3])

In [56]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [58]:
tensor * tensor

tensor([1, 4, 9])

In [62]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 39 µs, sys: 18 µs, total: 57 µs
Wall time: 61.5 µs


tensor(14)

In [61]:
%%time

tensor @ tensor

CPU times: user 194 µs, sys: 88 µs, total: 282 µs
Wall time: 235 µs


tensor(14)

In [85]:
%%time 
# Matric mutiplication by hand

value = 0
for i in range(len(tensor)):
    value = value + tensor[i] * tensor[i]
value

CPU times: user 1.46 ms, sys: 0 ns, total: 1.46 ms
Wall time: 1.03 ms


tensor(14)

In [70]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 69 µs, sys: 28 µs, total: 97 µs
Wall time: 65.1 µs


tensor(14)

In [86]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [87]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [88]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [89]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [91]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [92]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)


x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output: \n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Finding the min, max, mean, sum, etc (aggregation)

In [93]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [95]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [96]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# Change tensor datatype

In [99]:
# create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype, tensor.shape

(torch.float32, torch.Size([9]))

In [100]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing

In [106]:
# Create a tensor
import torch 

x = torch.arange(1., 9.)
x, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), 1)

In [128]:
# add an extra dimension
x_reshaped = x.reshape(1,8)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]), 2)

In [112]:
z =x.view(1,8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [113]:
# changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [125]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape, x_stacked.ndim

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.]]),
 torch.Size([8, 4]),
 2)

In [132]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])


In [133]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [134]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selectiing data from tensors)

In [136]:
# Create a tensor 
import torch      
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [137]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [144]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs

In [145]:
!nvidia-smi

Wed Oct 23 11:22:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8              14W /  80W |     17MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [146]:
# Check for GPU
import torch     
torch.cuda.is_available()

True

In [147]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [148]:
# Count number of devices
torch.cuda.device_count()

1

In [149]:
import torch     
torch.backends.mps.is_available()

False

In [150]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [151]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [154]:
# Create tensor (default on CPU)
tensor = torch.tensor([1,2,3])

print(tensor,tensor.ndim, tensor.shape, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) 1 torch.Size([3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [155]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [156]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [157]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')